# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# General
$filemanager = nautilus 
$applauncher = fuzzel
$terminal = ghostty
$idlehandler = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'
$browser = zen-browser
$steam = steam
$dick = vesktop
$ge = godot
$ve = shotcut
$pe = gimp
$sc = com.core447.StreamController
# Screenshots
$shot-region = hyprshot -m region
$shot-window = hyprshot -m window
$shot-screen = hyprshot -m output
